name: Rust

on:
  push:
    branches:
    - master
  pull_request:
  schedule:
    - cron:  '0 6 1 * *' # Run on the first day of every month at 06:00 UTC

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - name: Build
      run: cargo build --release --verbose
    # - name: Run tests
    #   run: cargo test --verbose
